---
namenode:
    image: bde2020/hadoop-namenode:1.0.0
    hostname: namenode
    container_name: namenode
    domainname: hadoop
    net: hadoop
    volumes:
        - ./data/namenode:/hadoop/dfs/name
    environment:
        - CLUSTER_NAME=test
    env_file:
        - ./hadoop.env
    ports:
        - "50070:50070"
        - "8020:8020"
        - "8081:8081"
datanode1:
    image: bde2020/hadoop-datanode:1.0.0
    domainname: hadoop
    hostname: datanode1
    container_name: datanode1
    net: hadoop
    volumes:
        - /hadoop/dfs/data
    env_file:
        - ./hadoop.env

datanode2:
    image: bde2020/hadoop-datanode:1.0.0
    domainname: hadoop
    hostname: datanode2
    container_name: datanode2
    net: hadoop
    volumes:
        - /hadoop/dfs/data
    env_file:
        - ./hadoop.env
jobmanager:
    build: ./flink
    container_name: jobmanager
    net: hadoop
    ports:
        - "48081:8081"
    command: jobmanager
    volumes:
        - conf:/usr/local/flink/conf
taskmanager:
    build: ./flink
    container_name: taskmanager
    net: hadoop
    command: taskmanager
    volumes_from:
        - jobmanager:ro
