---
version: '2'
services:
    namenode:
        image: bde2020/hadoop-namenode:1.0.0
        hostname: namenode
        container_name: namenode
        domainname: hadoop
        networks:
            - hadoop
        volumes:
            - ./data/namenode:/hadoop/dfs/name
        environment:
            - CLUSTER_NAME=test
        env_file:
            - ./hadoop.env
        ports:
            - "50070:50070"
            - "8020:8020"

    datanode:
        image: bde2020/hadoop-datanode:1.0.0
        domainname: hadoop
        networks:
            - hadoop
        volumes:
            - /hadoop/dfs/data
        env_file:
            - ./hadoop.env

networks:
    hadoop:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 10.100.0.0/20
                  gateway: 10.100.0.1
